id: I07752C7C
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:05:09.650778
last_modified: 2023-02-09 15:05:09.650883
source_metadata:
  title: 'MSV 1,05: Carmavastu'
  language: bo
bases:
  '2096':
    base_file: 2096.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
